services:

  gazie-app:
    #build:
    #  context: .
    image: gabrieleviv/gazie-docker:9.05
    container_name: gazie-app
    restart: no
    ports:
      - 8971:80
    environment:
      - MARIADB_ROOT_PASSWORD=gazieRootPassword
      - MARIADB_DATABASE=gazie
      - MARIADB_USER=gazie
      - MARIADB_PASSWORD=gaziePassword
      - DEBUG=true
    volumes:
      - ./data:/var/www/html/data
      - ./php.ini-development:/usr/local/etc/php/php.ini
      - ./php.ini-errors:/usr/local/etc/php/conf.d/errors.ini
      - ./phpinfo.php:/var/www/html/phpinfo.php
      - ./FoglioStileAssoSoftware.xsl:/var/www/html/library/include/FoglioStileAssoSoftware.xsl
    depends_on:
      gazie-db:
        condition: service_healthy

  gazie-db:
    image: mariadb:11.4.5
    container_name: gazie-db
    restart: no
    environment:
      - MARIADB_ROOT_PASSWORD=gazieRootPassword
      - MARIADB_DATABASE=gazie
      - MARIADB_USER=gazie
      - MARIADB_PASSWORD=gaziePassword
      - TZ=Europe/Rome
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 120s
      interval: 10s
      timeout: 30s
      retries: 3

  gazie-phpmyadmin:
        container_name: gazie-phpmyadmin
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - 8915:80
        environment:
           - PMA_HOST=gazie-db
           - MYSQL_ROOT_PASSWORD=gazieRootPassword
           - UPLOAD_LIMIT=1G
           - MAX_EXECUTION_TIME=600
        depends_on:
            gazie-db:
                condition: service_healthy
     
#  gazie-db-clean:
#    image: mariadb:10.11
#    container_name: gazie-db-clean
#    restart: no
#    environment:
#      - MARIADB_ROOT_PASSWORD=gazieRootPassword
#      - MARIADB_DATABASE=gazieclean
#      - MARIADB_USER=gazieclean
#      - MARIADB_PASSWORD=gazieCleanPassword
#    ports:
#      - 3307:3306
#    volumes:
#      - ./mysql-clean:/var/lib/mysql
#      - ./docker-entrypoint-initdb.d-clean:/docker-entrypoint-initdb.d
#    healthcheck:
#      #    test: exit 0
#      #    test: [ "CMD-SHELL", "mysqladmin" ,"ping", "-h", "localhost", "-u", "$$MYSQL_USER", "-p", "$$MYSQL_PASSWORD" ]
#      test: mysqladmin ping -h localhost -u $$MARIADB_USER -p$$MARIADB_PASSWORD || exit 1
#      # wait 10 seconds after the container is started
#      interval: 10s
#      # do the check and wait for 10s timeout
#      timeout:  10s
#      # repeat 3 times
#      retries:  3
#
#  bytebase:
#      container_name: bytebase
#      ports:
#        - 8080:8080
#      volumes:
#        - ./bytebase/data:/var/opt/bytebase
#      image: bytebase/bytebase:3.5.2
#      restart: no
